/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Configure.java
 *
 * Created on Aug 24, 2010, 10:14:35 AM
 */

package org.jemian.countdownj.Swing;

//########### SVN repository information ###################
//# $Date$
//# $Author$
//# $Revision$
//# $URL$
//# $Id$
//########### SVN repository information ###################

/**
 *
 * @author Pete
 */
public class Configure extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6246475747169907480L;

	/** Creates new form Configure */
    public Configure(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonDefaults = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        entryDiscussion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entryOvertime = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        entry_MsgPretalk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entry_MsgPresentation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        entry_MsgDiscussion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        entry_MsgOvertime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entry_MsgPaused = new javax.swing.JTextField();
        presetsTab = new javax.swing.JPanel();
        presetsTabPane = new javax.swing.JTabbedPane();
        tabA = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        entryA_ButtonLabel = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        entryA_Discussion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        entryA_Overtime = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        entryA_MsgPretalk = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        entryA_MsgPresentation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        entryA_MsgDiscussion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        entryA_MsgOvertime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        entryA_MsgPaused = new javax.swing.JTextField();
        tabB = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        entryB_ButtonLabel = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        entryB_Discussion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        entryB_Overtime = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        entryB_MsgPretalk = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        entryB_MsgPresentation = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        entryB_MsgDiscussion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        entryB_MsgOvertime = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        entryB_MsgPaused = new javax.swing.JTextField();
        tabC = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        entryC_ButtonLabel = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        entryC_Discussion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        entryC_Overtime = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        entryC_MsgPretalk = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        entryC_MsgPresentation = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        entryC_MsgDiscussion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        entryC_MsgOvertime = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        entryC_MsgPaused = new javax.swing.JTextField();
        tabD = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        entryD_ButtonLabel = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        entryD_Discussion = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        entryD_Overtime = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        entryD_MsgPretalk = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        entryD_MsgPresentation = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        entryD_MsgDiscussion = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        entryD_MsgOvertime = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        entryD_MsgPaused = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        buttonOk.setText("Ok");

        buttonDefaults.setText("defaults");

        buttonCancel.setText("cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDefaults, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonCancel)
                    .addComponent(buttonDefaults))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Configuration details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("time allowed for discussion");

        entryDiscussion.setText("{mm:ss | seconds}");
        entryDiscussion.setToolTipText("enter either minutes:seconds (12:30) or seconds (750)");

        jLabel3.setText("overtime reminder interval");

        entryOvertime.setText("{mm:ss | seconds}");
        entryOvertime.setToolTipText("3 bells will sound in overtime at this interval");

        jLabel4.setText("pre-talk message");

        entry_MsgPretalk.setText("{pre-talk message}");
        entry_MsgPretalk.setToolTipText("message to show before presentation negins");

        jLabel5.setText("presentation message");

        entry_MsgPresentation.setText("{presentation message}");
        entry_MsgPresentation.setToolTipText("message to show during presentation before discussion");

        jLabel6.setText("discussion message");

        entry_MsgDiscussion.setText("{discussion message}");
        entry_MsgDiscussion.setToolTipText("message to show during time allowed for discussion");

        jLabel7.setText("overtime message");

        entry_MsgOvertime.setText("{overtime message}");
        entry_MsgOvertime.setToolTipText("message to show when time has run out");

        jLabel8.setText("paused message");

        entry_MsgPaused.setText("{presentation paused message}");
        entry_MsgPaused.setToolTipText("message to show if presentation has been paused");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entryDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(entryOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entry_MsgPaused, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entry_MsgOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entry_MsgDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entry_MsgPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entry_MsgPretalk, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entryDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entryOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entry_MsgPretalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(entry_MsgPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(entry_MsgDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(entry_MsgOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(entry_MsgPaused, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("standard", jPanel3);

        presetsTabPane.setBackground(new java.awt.Color(204, 204, 204));

        tabA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel37.setText("button label");

        entryA_ButtonLabel.setText("{button label}");
        entryA_ButtonLabel.setToolTipText("such as \"inivited\", \"plenary\", \"contributed\", ...");

        jLabel9.setText("time allowed for discussion");

        entryA_Discussion.setText("{mm:ss | seconds}");
        entryA_Discussion.setToolTipText("enter either minutes:seconds (12:30) or seconds (750)");

        jLabel10.setText("overtime reminder interval");

        entryA_Overtime.setText("{mm:ss | seconds}");
        entryA_Overtime.setToolTipText("3 bells will sound in overtime at this interval");

        jLabel11.setText("pre-talk message");

        entryA_MsgPretalk.setText("{pre-talk message}");
        entryA_MsgPretalk.setToolTipText("message to show before presentation negins");

        jLabel12.setText("presentation message");

        entryA_MsgPresentation.setText("{presentation message}");
        entryA_MsgPresentation.setToolTipText("message to show during presentation before discussion");

        jLabel13.setText("discussion message");

        entryA_MsgDiscussion.setText("{discussion message}");
        entryA_MsgDiscussion.setToolTipText("message to show during time allowed for discussion");

        jLabel14.setText("overtime message");

        entryA_MsgOvertime.setText("{overtime message}");
        entryA_MsgOvertime.setToolTipText("message to show when time has run out");

        jLabel15.setText("paused message");

        entryA_MsgPaused.setText("{presentation paused message}");
        entryA_MsgPaused.setToolTipText("message to show if presentation has been paused");

        javax.swing.GroupLayout tabALayout = new javax.swing.GroupLayout(tabA);
        tabA.setLayout(tabALayout);
        tabALayout.setHorizontalGroup(
            tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabALayout.createSequentialGroup()
                            .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(38, 38, 38)
                            .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entryA_Discussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(entryA_Overtime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(tabALayout.createSequentialGroup()
                        .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(90, 90, 90)
                        .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryA_MsgPaused, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryA_MsgOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryA_MsgDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryA_MsgPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryA_MsgPretalk, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(tabALayout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(entryA_ButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        tabALayout.setVerticalGroup(
            tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(entryA_ButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(entryA_Discussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(entryA_Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(entryA_MsgPretalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(entryA_MsgPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(entryA_MsgDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(entryA_MsgOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(entryA_MsgPaused, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        presetsTabPane.addTab("button < A >", tabA);

        tabB.setBackground(new java.awt.Color(204, 204, 204));

        jLabel38.setText("button label");

        entryB_ButtonLabel.setText("{button label}");
        entryB_ButtonLabel.setToolTipText("such as \"inivited\", \"plenary\", \"contributed\", ...");

        jLabel16.setText("time allowed for discussion");

        entryB_Discussion.setText("{mm:ss | seconds}");
        entryB_Discussion.setToolTipText("enter either minutes:seconds (12:30) or seconds (750)");

        jLabel17.setText("overtime reminder interval");

        entryB_Overtime.setText("{mm:ss | seconds}");
        entryB_Overtime.setToolTipText("3 bells will sound in overtime at this interval");

        jLabel18.setText("pre-talk message");

        entryB_MsgPretalk.setText("{pre-talk message}");
        entryB_MsgPretalk.setToolTipText("message to show before presentation negins");

        jLabel19.setText("presentation message");

        entryB_MsgPresentation.setText("{presentation message}");
        entryB_MsgPresentation.setToolTipText("message to show during presentation before discussion");

        jLabel20.setText("discussion message");

        entryB_MsgDiscussion.setText("{discussion message}");
        entryB_MsgDiscussion.setToolTipText("message to show during time allowed for discussion");

        jLabel21.setText("overtime message");

        entryB_MsgOvertime.setText("{overtime message}");
        entryB_MsgOvertime.setToolTipText("message to show when time has run out");

        jLabel22.setText("paused message");

        entryB_MsgPaused.setText("{presentation paused message}");
        entryB_MsgPaused.setToolTipText("message to show if presentation has been paused");

        javax.swing.GroupLayout tabBLayout = new javax.swing.GroupLayout(tabB);
        tabB.setLayout(tabBLayout);
        tabBLayout.setHorizontalGroup(
            tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(tabBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabBLayout.createSequentialGroup()
                            .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGap(38, 38, 38)
                            .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entryB_Discussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(entryB_Overtime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(tabBLayout.createSequentialGroup()
                        .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(90, 90, 90)
                        .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryB_MsgPaused, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryB_MsgOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryB_MsgDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryB_MsgPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryB_MsgPretalk, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(tabBLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(entryB_ButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        tabBLayout.setVerticalGroup(
            tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(entryB_ButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(entryB_Discussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(entryB_Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(entryB_MsgPretalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(entryB_MsgPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(entryB_MsgDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(entryB_MsgOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(entryB_MsgPaused, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        presetsTabPane.addTab("button < B >", tabB);

        tabC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel39.setText("button label");

        entryC_ButtonLabel.setText("{button label}");
        entryC_ButtonLabel.setToolTipText("such as \"inivited\", \"plenary\", \"contributed\", ...");

        jLabel23.setText("time allowed for discussion");

        entryC_Discussion.setText("{mm:ss | seconds}");
        entryC_Discussion.setToolTipText("enter either minutes:seconds (12:30) or seconds (750)");

        jLabel24.setText("overtime reminder interval");

        entryC_Overtime.setText("{mm:ss | seconds}");
        entryC_Overtime.setToolTipText("3 bells will sound in overtime at this interval");

        jLabel25.setText("pre-talk message");

        entryC_MsgPretalk.setText("{pre-talk message}");
        entryC_MsgPretalk.setToolTipText("message to show before presentation negins");

        jLabel26.setText("presentation message");

        entryC_MsgPresentation.setText("{presentation message}");
        entryC_MsgPresentation.setToolTipText("message to show during presentation before discussion");

        jLabel27.setText("discussion message");

        entryC_MsgDiscussion.setText("{discussion message}");
        entryC_MsgDiscussion.setToolTipText("message to show during time allowed for discussion");

        jLabel28.setText("overtime message");

        entryC_MsgOvertime.setText("{overtime message}");
        entryC_MsgOvertime.setToolTipText("message to show when time has run out");

        jLabel29.setText("paused message");

        entryC_MsgPaused.setText("{presentation paused message}");
        entryC_MsgPaused.setToolTipText("message to show if presentation has been paused");

        javax.swing.GroupLayout tabCLayout = new javax.swing.GroupLayout(tabC);
        tabC.setLayout(tabCLayout);
        tabCLayout.setHorizontalGroup(
            tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(tabCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabCLayout.createSequentialGroup()
                            .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24))
                            .addGap(38, 38, 38)
                            .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entryC_Discussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(entryC_Overtime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(tabCLayout.createSequentialGroup()
                        .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(90, 90, 90)
                        .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryC_MsgPaused, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryC_MsgOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryC_MsgDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryC_MsgPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryC_MsgPretalk, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(tabCLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(entryC_ButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        tabCLayout.setVerticalGroup(
            tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(entryC_ButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(entryC_Discussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(entryC_Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(entryC_MsgPretalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(entryC_MsgPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(entryC_MsgDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(entryC_MsgOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(entryC_MsgPaused, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        presetsTabPane.addTab("button < C >", tabC);

        tabD.setBackground(new java.awt.Color(204, 204, 204));

        jLabel40.setText("button label");

        entryD_ButtonLabel.setText("{button label}");
        entryD_ButtonLabel.setToolTipText("such as \"inivited\", \"plenary\", \"contributed\", ...");

        jLabel30.setText("time allowed for discussion");

        entryD_Discussion.setText("{mm:ss | seconds}");
        entryD_Discussion.setToolTipText("enter either minutes:seconds (12:30) or seconds (750)");

        jLabel31.setText("overtime reminder interval");

        entryD_Overtime.setText("{mm:ss | seconds}");
        entryD_Overtime.setToolTipText("3 bells will sound in overtime at this interval");

        jLabel32.setText("pre-talk message");

        entryD_MsgPretalk.setText("{pre-talk message}");
        entryD_MsgPretalk.setToolTipText("message to show before presentation negins");

        jLabel33.setText("presentation message");

        entryD_MsgPresentation.setText("{presentation message}");
        entryD_MsgPresentation.setToolTipText("message to show during presentation before discussion");

        jLabel34.setText("discussion message");

        entryD_MsgDiscussion.setText("{discussion message}");
        entryD_MsgDiscussion.setToolTipText("message to show during time allowed for discussion");

        jLabel35.setText("overtime message");

        entryD_MsgOvertime.setText("{overtime message}");
        entryD_MsgOvertime.setToolTipText("message to show when time has run out");

        jLabel36.setText("paused message");

        entryD_MsgPaused.setText("{presentation paused message}");
        entryD_MsgPaused.setToolTipText("message to show if presentation has been paused");

        javax.swing.GroupLayout tabDLayout = new javax.swing.GroupLayout(tabD);
        tabD.setLayout(tabDLayout);
        tabDLayout.setHorizontalGroup(
            tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(tabDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabDLayout.createSequentialGroup()
                            .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addGap(38, 38, 38)
                            .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entryD_Discussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(entryD_Overtime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                    .addGroup(tabDLayout.createSequentialGroup()
                        .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(90, 90, 90)
                        .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryD_MsgPaused, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryD_MsgOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryD_MsgDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryD_MsgPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(entryD_MsgPretalk, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(tabDLayout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(entryD_ButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        tabDLayout.setVerticalGroup(
            tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGap(0, 272, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(entryD_ButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(entryD_Discussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(entryD_Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(entryD_MsgPretalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(entryD_MsgPresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(entryD_MsgDiscussion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(entryD_MsgOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(entryD_MsgPaused, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        presetsTabPane.addTab("button < D >", tabD);

        javax.swing.GroupLayout presetsTabLayout = new javax.swing.GroupLayout(presetsTab);
        presetsTab.setLayout(presetsTabLayout);
        presetsTabLayout.setHorizontalGroup(
            presetsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(presetsTabPane)
                .addContainerGap())
        );
        presetsTabLayout.setVerticalGroup(
            presetsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(presetsTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("presets", presetsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configure dialog = new Configure(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDefaults;
    private javax.swing.JButton buttonOk;
    private javax.swing.JTextField entryA_ButtonLabel;
    private javax.swing.JTextField entryA_Discussion;
    private javax.swing.JTextField entryA_MsgDiscussion;
    private javax.swing.JTextField entryA_MsgOvertime;
    private javax.swing.JTextField entryA_MsgPaused;
    private javax.swing.JTextField entryA_MsgPresentation;
    private javax.swing.JTextField entryA_MsgPretalk;
    private javax.swing.JTextField entryA_Overtime;
    private javax.swing.JTextField entryB_ButtonLabel;
    private javax.swing.JTextField entryB_Discussion;
    private javax.swing.JTextField entryB_MsgDiscussion;
    private javax.swing.JTextField entryB_MsgOvertime;
    private javax.swing.JTextField entryB_MsgPaused;
    private javax.swing.JTextField entryB_MsgPresentation;
    private javax.swing.JTextField entryB_MsgPretalk;
    private javax.swing.JTextField entryB_Overtime;
    private javax.swing.JTextField entryC_ButtonLabel;
    private javax.swing.JTextField entryC_Discussion;
    private javax.swing.JTextField entryC_MsgDiscussion;
    private javax.swing.JTextField entryC_MsgOvertime;
    private javax.swing.JTextField entryC_MsgPaused;
    private javax.swing.JTextField entryC_MsgPresentation;
    private javax.swing.JTextField entryC_MsgPretalk;
    private javax.swing.JTextField entryC_Overtime;
    private javax.swing.JTextField entryD_ButtonLabel;
    private javax.swing.JTextField entryD_Discussion;
    private javax.swing.JTextField entryD_MsgDiscussion;
    private javax.swing.JTextField entryD_MsgOvertime;
    private javax.swing.JTextField entryD_MsgPaused;
    private javax.swing.JTextField entryD_MsgPresentation;
    private javax.swing.JTextField entryD_MsgPretalk;
    private javax.swing.JTextField entryD_Overtime;
    private javax.swing.JTextField entryDiscussion;
    private javax.swing.JTextField entryOvertime;
    private javax.swing.JTextField entry_MsgDiscussion;
    private javax.swing.JTextField entry_MsgOvertime;
    private javax.swing.JTextField entry_MsgPaused;
    private javax.swing.JTextField entry_MsgPresentation;
    private javax.swing.JTextField entry_MsgPretalk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel presetsTab;
    private javax.swing.JTabbedPane presetsTabPane;
    private javax.swing.JPanel tabA;
    private javax.swing.JPanel tabB;
    private javax.swing.JPanel tabC;
    private javax.swing.JPanel tabD;
    // End of variables declaration//GEN-END:variables

}
